version: "3.9"

services:
  api:
    build: .
    container_name: nexygen-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped
